#!/usr/bin/env python3
"""Build core/tg_emoji_sheet.c and include/tg_emoji_sheet.h from Noto Emoji PNGs.

Input: a directory holding emoji_u<hex>.png (the 128 px set of
https://github.com/googlefonts/noto-emoji, OFL 1.1) for the codepoints in
the curated list below. Output: 16x16 glyphs on a shared 255 colour palette,
index 0 = transparent, as C arrays, plus a preview PNG.

The curated list is the emoji the client already maps to text emoticons in
core/tg_mtproto_probe.c (tg_mtproto_display_emoticon): what can be sent is
what can be read back. Three of those (2190, 2192, 2713) are text symbols
with no Noto image and stay emoticon-only.
"""
import os, re, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, 'core', 'tg_mtproto_probe.c')
SIZE = 16

def curated():
    s = open(SRC, encoding='utf-8').read()
    i = s.index('static const char *tg_mtproto_display_emoticon')
    j = s.index('\n}\n', i)
    return [int(m, 16) for m in re.findall(r'case 0x([0-9a-f]+)UL', s[i:j])]

def main(png_dir, preview=None):
    cps = curated()
    glyphs = []
    for cp in cps:
        f = os.path.join(png_dir, 'emoji_u%x.png' % cp)
        if not os.path.exists(f):
            print('skip %x: no image' % cp, file=sys.stderr)
            continue
        im = Image.open(f).convert('RGBA').resize((SIZE, SIZE), Image.LANCZOS)
        glyphs.append((cp, im))
    # one palette for every glyph: quantise a strip of all of them together
    strip = Image.new('RGBA', (SIZE * len(glyphs), SIZE), (0, 0, 0, 0))
    for k, (_, im) in enumerate(glyphs):
        strip.paste(im, (k * SIZE, 0))
    rgb = Image.new('RGB', strip.size, (0, 0, 0))
    rgb.paste(strip, mask=strip.split()[3])
    q = rgb.quantize(colors=255, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    pal = q.getpalette()[:255 * 3]
    alpha = strip.split()[3]
    pixels = []
    for k in range(len(glyphs)):
        cell = []
        for y in range(SIZE):
            for x in range(SIZE):
                px, py = k * SIZE + x, y
                cell.append(0 if alpha.getpixel((px, py)) < 128 else q.getpixel((px, py)) + 1)
        pixels.append(cell)
    # C output
    c = []
    c.append('/* Generated by scripts/gen-emoji-sheet.py from Noto Emoji (OFL 1.1, see\n'
             '   third_party/noto-emoji). Do not edit; regenerate. %d glyphs of %dx%d,\n'
             '   one shared palette, index 0 transparent. */\n' % (len(glyphs), SIZE, SIZE))
    c.append('#include "tg_emoji_sheet.h"\n\n')
    c.append('const unsigned long tg_emoji_sheet_count = %dUL;\n' % len(glyphs))
    c.append('const unsigned long tg_emoji_sheet_codepoints[%d] = {\n' % len(glyphs))
    for k, (cp, _) in enumerate(glyphs):
        c.append('    0x%xUL,%s' % (cp, '\n' if k % 6 == 5 else ' '))
    c.append('\n};\n')
    c.append('const unsigned char tg_emoji_sheet_palette[255][3] = {\n')
    for k in range(255):
        c.append('    {%d,%d,%d},%s' % (pal[k*3], pal[k*3+1], pal[k*3+2], '\n' if k % 6 == 5 else ' '))
    c.append('\n};\n')
    c.append('const unsigned char tg_emoji_sheet_pixels[%d][%d] = {\n' % (len(glyphs), SIZE * SIZE))
    for k, cell in enumerate(pixels):
        c.append('    { /* %x */\n' % glyphs[k][0])
        for y in range(SIZE):
            c.append('      ' + ','.join('%3d' % v for v in cell[y*SIZE:(y+1)*SIZE]) + ',\n')
        c.append('    },\n')
    c.append('};\n')
    open(os.path.join(ROOT, 'core', 'tg_emoji_sheet.c'), 'w').write(''.join(c))
    h = '''/* Emoji glyph sheet: %d glyphs of %dx%d pixels on one shared palette, index 0
   transparent. Derived from Noto Emoji (OFL 1.1), see third_party/noto-emoji.
   Generated by scripts/gen-emoji-sheet.py; do not edit by hand. */
#ifndef TG_EMOJI_SHEET_H
#define TG_EMOJI_SHEET_H

#define TG_EMOJI_GLYPH_SIZE %d

extern const unsigned long tg_emoji_sheet_count;
extern const unsigned long tg_emoji_sheet_codepoints[%d];
extern const unsigned char tg_emoji_sheet_palette[255][3];
extern const unsigned char tg_emoji_sheet_pixels[%d][%d];

#endif
''' % (len(glyphs), SIZE, SIZE, SIZE, len(glyphs), len(glyphs), SIZE * SIZE)
    open(os.path.join(ROOT, 'include', 'tg_emoji_sheet.h'), 'w').write(h)
    if preview:
        cols = 16
        rows = (len(glyphs) + cols - 1) // cols
        for scale, name in ((1, preview), (4, preview.replace('.png', '-4x.png'))):
            im = Image.new('RGB', (cols * (SIZE + 2) * scale, rows * (SIZE + 2) * scale), (40, 44, 52))
            for k, cell in enumerate(pixels):
                gx, gy = (k % cols) * (SIZE + 2) + 1, (k // cols) * (SIZE + 2) + 1
                for y in range(SIZE):
                    for x in range(SIZE):
                        v = cell[y * SIZE + x]
                        if v:
                            col = (pal[(v-1)*3], pal[(v-1)*3+1], pal[(v-1)*3+2])
                            for dy in range(scale):
                                for dx in range(scale):
                                    im.putpixel(((gx + x) * scale + dx, (gy + y) * scale + dy), col)
            im.save(name)
    print('glyphs: %d, palette: 255, bytes: %d' % (len(glyphs), len(glyphs) * SIZE * SIZE + 255 * 3))

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
