/* Emoji glyph sheet: 109 glyphs of 16x16 pixels on one shared palette, index 0
   transparent. Derived from Noto Emoji (OFL 1.1), see third_party/noto-emoji.
   Generated by scripts/gen-emoji-sheet.py; do not edit by hand. */
#ifndef TG_EMOJI_SHEET_H
#define TG_EMOJI_SHEET_H

#define TG_EMOJI_GLYPH_SIZE 16

extern const unsigned long tg_emoji_sheet_count;
extern const unsigned long tg_emoji_sheet_codepoints[109];
extern const unsigned char tg_emoji_sheet_palette[255][3];
extern const unsigned char tg_emoji_sheet_pixels[109][256];

#endif
